library(tidyverse)
library(mosaic)
d <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/9f7aa782208114dd99dc33f94704426f703b908e/zombies.csv", col_names = TRUE)
(m <- lm(data = d, height ~ weight))
SSY <- sum((m$model$height - mean(m$model$height))^2)
SSR <- sum((m$fitted.values - mean(m$model$height))^2)
SSE <- sum((m$model$height - mean(m$fitted.values))^2)
MSY <- SSY/(nrow(d)-1)
MSR <- SSR/1
MSE <- SSE/(nrow(d)-2)
fratio <- MSR/MSE #high is well explained, low is not very well-explained
pf(q = fratio, df1 = 1, df2 = 998, lower.tail = FALSE)
mosaic::plotDist("f", df1 =1, df2 = 998)
(rsq <- SSR/SSY)
anova(m)
#trying again
new_d <- tibble(x = rnorm(1000, mean = 100, sd = 25), y = rnorm(1000, mean = 10, sd =2))
plot(new_d$x, new_d$y)
m <- (lm(y~x, data = new_d))
summary(m)
SSY <- sum((m$model$y - mean(m$model$y))^2)
SSR <- sum((m$fitted.values - mean(m$model$y))^2)
SSE <- sum((m$model$y - mean(m$fitted.values))^2)
MSY <- SSY/(nrow(new_d)-1)
MSR <- SSR/1
MSE <- SSE/(nrow(new_d)-2)
(fratio <- MSR/MSE)
pf(q=fratio, df1 = 1, df2 = nrow(new_d)-1-1, lower.tail = FALSE)
anova(m)
#challenge
d <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/KamilarAndCooperData.csv", col_names = TRUE)
plot(d$MaxLongevity_m~d$Body_mass_female_mean)
(m1 <- lm(data = d, MaxLongevity_m ~ Body_mass_female_mean))
(m2 <- lm(data = d, MaxLongevity_m ~ log(Body_mass_female_mean)))
(m3 <- lm(data = d, log(MaxLongevity_m) ~ log(Body_mass_female_mean)))
par (mfrow = c(2,2))
plot(m1)
par (mfrow = c(2,2))
plot(m2)
par (mfrow = c(2,2))
plot(m3)
resid1 <- resid(m1)
hist(resid1)
resid2 <- resid(m2)
hist(resid2)
resid3 <- resid (m3)
hist(resid3)
car::qqPlot(m1)
car::qqPlot(m2)
car::qqPlot(m3)
shapiro.test(m1$residuals)
shapiro.test(m2$residuals)
shapiro.test(m3$residuals)
#categorical predictors
d <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/AVONETdataset1.csv", col_names = TRUE)
d <- d |>
  select(Species1,Family1, Order1, Beak.Width, Beak.Depth, Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level,Trophic.Niche,Min.Latitude,Max.Latitude,Centroid.Latitude,Range.Size)
glimpse(d)
table(d$Habitat)
nrow(d)
